apiVersion: v1
kind: LoomPipeline
pipeline:
  id: build-docker-image
  name: Build Docker Image Pipeline
  vars:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

  stages:
    - name: build
      job: build-image

  jobs:
    build-image:
      path: ${LOOM_CLI_IMAGE}
      command: build_image
      services: ["docker:24-dind"]
      input:
        params:
          systems.git.url: ${GITLAB_URL}
          systems.git.user: gitlab-ci-token
          systems.git.branch: master
          systems.registry.url: ${REGISTRY_URL}
          systems.registry.user: arala
          params.dockerfile: "src/Dockerfile"
          params.image: "arala/loom_cli"
          params.tag: "latest"

        secure_params:
          systems.git.token: ${GITLAB_PASSWORD}
          systems.registry.password: ${REGISTRY_PASSWORD}

      when:
        statuses: SUCCESS
